-- If you are using Hibernate as the JPA provider, you can use this file to load seed data into the database using SQL statements
-- The portable approach is to use a startup component (such as the @PostConstruct method of a @Startup @Singleton) or observe a lifecycle event fired by Seam Servlet
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU76E15H501X', 'Luca', 'Stancapiano', 0, 0, '1B', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('SANLCU76E15H501X', 'Davide', 'Barillari', 0, 0, '2B', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STHLCU76E15H501X', 'Beppe', 'Grillo', 0, 0, '3B', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCO76E15H501X', 'Manlio', 'Di Stefano', 0, 0, '4B', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STN9CU76E15H501X', 'Sebastiano', 'Cubeddu', 0, 0, '5B', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNMCU76E15H501X', 'Maurizio', 'Celani', 0, 0, '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU76E15H601X', 'Domenico', 'Gigliotti', 0, 0, '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU76E15U801X', 'Laura', 'Spinella', 0, 0, '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU99I15H501X', 'Laura', 'Alessandrini', 0, 0, '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCY98E15H501X', 'Laura', 'Santoni', 0, 0, '5A', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNUQ786E15H501X', 'Giuliano', 'Santoboni', 0, 0, '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU76E15H502Y', 'Maria', 'Naimo', 0, 0, '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU73T85H501X', 'Raffaele', 'Bonaffini', 0, 0, '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('ABNLCU76E15H501X', 'Fabrizio', 'Fossati', 0, 0, '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('OPILCU76E15H501X', 'Patrizia', 'Fontana', 0, 0, '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('BHJLCU76E15H501X', 'Gladys', 'Carrizales', 0, 0, '1D', 'maiorana');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('AQWLCU76E15H501X', 'Alessandro', 'Toro', 0, 0, '1A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('MLLLCU76E15H501X', 'Daniele', 'Ronci', 0, 0, '2A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('OOOLCU76E15H501X', 'Luigi', 'Di Maio', 0, 0, '3A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('QWERCU76E15H501X', 'Claudio', 'Cos', 0, 0, '4A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('MJKLCU76E15H501X', 'Antonino', 'Briganti', 0, 0, '5A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('YYTLCU76E15H501X', 'Luigi', 'Briganti', 0, 0, '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('AQWLC576E15H501X', 'Matteo', 'Castorino', 0, 0, '2C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('NNBLCU76E15H501X', 'Stefano', 'Bufalieri', 0, 0, '3C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('NNJLCU76E15H501X', 'Giuseppe', 'Conte', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('SSALCU76E15H501X', 'Giulia', 'Grillo', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('IIYLCU76E15H501X', 'Riccardo', 'Fraccaro', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('HJULCU76E15H501X', 'Alfonso', 'Bonafede', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('IIVLCU76E15H501X', 'Valerio', 'Novelli', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('STNLCU75SZ3H501X', 'Valentina', 'Corrado', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('AAAACU76E15H501X', 'Roberta', 'Lombardi', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('ABCLCU76E15H501X', 'Roberta', 'Della Casa', 0, 0, '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('GHYYCU76E15H501X', 'Virginia', 'Raggi', 0, 0, '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('DDSLCU76E15H501X', 'Marcello', 'De Vito', 0, 0, '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('VVSLCU76E15H501X', 'Giuseppe', 'Bonaventura', 0, 0, '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, income, monthquote, room, school) values ('IIILCU76E15H501X', 'Alessandro', 'Cocchiarella', 0, 0, '1C', 'cornelionepote');