-- If you are using Hibernate as the JPA provider, you can use this file to load seed data into the database using SQL statements
-- The portable approach is to use a startup component (such as the @PostConstruct method of a @Startup @Singleton) or observe a lifecycle event fired by Seam Servlet
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU76E15H501X', 'Luca', 'Stancapiano', 230000, '1B', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('SANLCU76E15H501X', 'Davide', 'Barillari', 10000, '2B', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STHLCU76E15H501X', 'Beppe', 'Grillo', 11000, '3B', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCO76E15H501X', 'Manlio', 'Di Stefano', 6000, '4B', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STN9CU76E15H501X', 'Sebastiano', 'Cubeddu', 5000, '5B', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNMCU76E15H501X', 'Maurizio', 'Celani', 1000, '1A', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU76E15H601X', 'Domenico', 'Gigliotti', 20000, '1A', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU76E15U801X', 'Laura', 'Spinella', 12000, '1A', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU99I15H501X', 'Laura', 'Alessandrini', 15000, '1A', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCY98E15H501X', 'Laura', 'Santoni', 60000, '5A', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNUQ786E15H501X', 'Giuliano', 'Santoboni', 90000, '5C', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU76E15H502Y', 'Maria', 'Naimo', 84000, '5C', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU73T85H501X', 'Raffaele', 'Bonaffini', 12300, '5C', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('ABNLCU76E15H501X', 'Fabrizio', 'Fossati', 100000, '5C', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('OPILCU76E15H501X', 'Patrizia', 'Fontana', 3400, '5C', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('BHJLCU76E15H501X', 'Gladys', 'Carrizales', 200000, '1D', 'donlorenzomilani');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('AQWLCU76E15H501X', 'Alessandro', 'Toro', 10000, '1A', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('MLLLCU76E15H501X', 'Daniele', 'Ronci', 11000, '2A', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('OOOLCU76E15H501X', 'Luigi', 'Di Maio', 14000, '3A', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('QWERCU76E15H501X', 'Claudio', 'Cos', 16000, '4A', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('MJKLCU76E15H501X', 'Antonino', 'Briganti', 12300, '5A', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('YYTLCU76E15H501X', 'Luigi', 'Briganti', 2000, '1C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('AQWLC576E15H501X', 'Matteo', 'Castorino', 3000, '2C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('NNBLCU76E15H501X', 'Stefano', 'Bufalieri', 14000, '3C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('NNJLCU76E15H501X', 'Giuseppe', 'Conte', 450000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('SSALCU76E15H501X', 'Giulia', 'Grillo', 45000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('IIYLCU76E15H501X', 'Riccardo', 'Fraccaro', 45000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('HJULCU76E15H501X', 'Alfonso', 'Bonafede', 12000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('IIVLCU76E15H501X', 'Valerio', 'Novelli', 13000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('STNLCU75SZ3H501X', 'Valentina', 'Corrado', 6000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('AAAACU76E15H501X', 'Roberta', 'Lombardi', 8000, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('ABCLCU76E15H501X', 'Roberta', 'Della Casa', 3400, '4C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('GHYYCU76E15H501X', 'Virginia', 'Raggi', 12000, '1C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('DDSLCU76E15H501X', 'Marcello', 'De Vito', 1200, '1C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('VVSLCU76E15H501X', 'Giuseppe', 'Bonaventura', 45000, '1C', 'edoardodefilippo');
insert into PUPILENTITY (id, name, surname, income, room, school) values ('IIILCU76E15H501X', 'Alessandro', 'Cocchiarella', 64000, '1C', 'edoardodefilippo');