-- If you are using Hibernate as the JPA provider, you can use this file to load seed data into the database using SQL statements
-- The portable approach is to use a startup component (such as the @PostConstruct method of a @Startup @Singleton) or observe a lifecycle event fired by Seam Servlet
insert into PUPILENTITY (id, name, surname, room, school) values (1, 'Luca', 'Stancapiano', '1B', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (2, 'Davide', 'Barillari', '2B', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (3, 'Beppe', 'Grillo', '3B', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (4, 'Manlio', 'Di Stefano', '4B', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (5, 'Sebastiano', 'Cubeddu', '5B', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (6, 'Maurizio', 'Celani', '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (7, 'Domenico', 'Gigliotti', '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (8, 'Laura', 'Spinella', '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (9, 'Laura', 'Alessandrini', '1A', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (10, 'Laura', 'Santoni', '5A', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (11, 'Giuliano', 'Santoboni', '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (12, 'Maria', 'Naimo', '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (13, 'Raffaele', 'Bonaffini', '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (14, 'Fabrizio', 'Fossati', '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (15, 'Patrizia', 'Fontana', '5C', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (16, 'Gladys', 'Carrizales', '1D', 'maiorana');
insert into PUPILENTITY (id, name, surname, room, school) values (17, 'Alessandro', 'Toro', '1A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (18, 'Daniele', 'Ronci', '2A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (19, 'Luigi', 'Di Maio', '3A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (20, 'Claudio', 'Cos', '4A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (21, 'Antonino', 'Briganti', '5A', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (22, 'Luigi', 'Briganti', '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (23, 'Matteo', 'Castorino', '2C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (24, 'Stefano', 'Bufalieri', '3C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (25, 'Giuseppe', 'Conte', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (26, 'Giulia', 'Grillo', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (27, 'Riccardo', 'Fraccaro', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (28, 'Alfonso', 'Bonafede', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (29, 'Valerio', 'Novelli', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (30, 'Valentina', 'Corrado', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (31, 'Roberta', 'Lombardi', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (32, 'Roberta', 'Della Casa', '4C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (33, 'Virginia', 'Raggi', '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (34, 'Marcello', 'De Vito', '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (35, 'Giuseppe', 'Bonaventura', '1C', 'cornelionepote');
insert into PUPILENTITY (id, name, surname, room, school) values (36, 'Alessandro', 'Cocchiarella', '1C', 'cornelionepote');