PrimeFaces.locales['it'] = {
	closeText : 'Chiudi',
	prevText : 'Precedente',
	nextText : 'Prossimo',
	monthNames : [ 'Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno',
			'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre' ],
	monthNamesShort : [ 'Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago',
			'Set', 'Ott', 'Nov', 'Dec' ],
	dayNames : [ 'Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì',
			'Sabato' ],
	dayNamesShort : [ 'Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab' ],
	dayNamesMin : [ 'D', 'L', 'M', 'M', 'G', 'V', 'S' ],
	weekHeader : 'Settimana',
	firstDay : 1,
	isRTL : false,
	showMonthAfterYear : false,
	yearSuffix : '',
	timeOnlyTitle : 'Scegli l\'orario',
	timeText : 'Orario',
	hourText : 'Ore',
	minuteText : 'Minuti',
	secondText : 'Secondi',
	currentText : 'Adesso',
	ampm : false,
	month : 'Mese',
	week : 'Settimana',
	day : 'Giorno',
	allDayText : 'Tutti giorni'
};